// <auto-generated />
using System;
using FleetTracker.Services.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FleetTracker.Services.Data.Migrations
{
    [DbContext(typeof(FleetTrackerDbContext))]
    [Migration("20260602154919_MaintenanceCostPrecision")]
    partial class MaintenanceCostPrecision
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<string>("DriversLicense")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.RentalAgreement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("ActualReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("AgreementNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<Guid?>("CustomerId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("EndingMileage")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpectedReturnDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("PickupDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("StartingMileage")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("VehicleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AgreementNumber")
                        .IsUnique();

                    b.HasIndex("CustomerId");

                    b.HasIndex("VehicleId");

                    b.ToTable("RentalAgreements");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Vehicle", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Class")
                        .HasColumnType("int");

                    b.Property<decimal>("DailyRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("LicensePlate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("VIN")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VIN")
                        .IsUnique();

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Customer", b =>
                {
                    b.OwnsOne("FleetTracker.Services.Core.Models.ContactInfo", "Contact", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Email")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactEmail");

                            b1.Property<string>("Name")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactName");

                            b1.Property<string>("PhoneNumber")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("ContactPhone");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("FleetTracker.Services.Core.Models.Address", "HomeAddress", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeCity");

                            b1.Property<string>("Country")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeCountry");

                            b1.Property<string>("State")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeState");

                            b1.Property<string>("Street")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeStreet");

                            b1.Property<string>("Zip")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)")
                                .HasColumnName("HomeZip");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.OwnsOne("FleetTracker.Services.Core.Models.PaymentInformation", "PaymentInformation", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("CustomerId");

                            b1.ToTable("Customers");

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");

                            b1.OwnsOne("FleetTracker.Services.Core.Models.CreditCard", "CreditCard", b2 =>
                                {
                                    b2.Property<Guid>("PaymentInformationCustomerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("CardHolderName")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CreditCardHolder");

                                    b2.Property<string>("CardNumber")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CreditCardNumber");

                                    b2.Property<string>("Cvv")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CreditCardCvv");

                                    b2.Property<string>("ExpirationDate")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("CreditCardExpiration");

                                    b2.HasKey("PaymentInformationCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentInformationCustomerId");
                                });

                            b1.OwnsOne("FleetTracker.Services.Core.Models.Address", "BillingAddress", b2 =>
                                {
                                    b2.Property<Guid>("PaymentInformationCustomerId")
                                        .HasColumnType("uniqueidentifier");

                                    b2.Property<string>("City")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BillingCity");

                                    b2.Property<string>("Country")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BillingCountry");

                                    b2.Property<string>("State")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BillingState");

                                    b2.Property<string>("Street")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BillingStreet");

                                    b2.Property<string>("Zip")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)")
                                        .HasColumnName("BillingZip");

                                    b2.HasKey("PaymentInformationCustomerId");

                                    b2.ToTable("Customers");

                                    b2.WithOwner()
                                        .HasForeignKey("PaymentInformationCustomerId");
                                });

                            b1.Navigation("BillingAddress")
                                .IsRequired();

                            b1.Navigation("CreditCard")
                                .IsRequired();
                        });

                    b.Navigation("Contact")
                        .IsRequired();

                    b.Navigation("HomeAddress")
                        .IsRequired();

                    b.Navigation("PaymentInformation")
                        .IsRequired();
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.RentalAgreement", b =>
                {
                    b.HasOne("FleetTracker.Services.Core.Models.Customer", "Customer")
                        .WithMany("RentalHistory")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("FleetTracker.Services.Core.Models.Vehicle", "Vehicle")
                        .WithMany("RentalHistory")
                        .HasForeignKey("VehicleId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Customer");

                    b.Navigation("Vehicle");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Vehicle", b =>
                {
                    b.OwnsMany("FleetTracker.Services.Core.Models.MaintenanceRecord", "MaintenanceHistory", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uniqueidentifier");

                            b1.Property<decimal>("Cost")
                                .HasColumnType("decimal(18,2)");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("nvarchar(max)");

                            b1.Property<DateTime>("ServiceDate")
                                .HasColumnType("datetime2");

                            b1.Property<int>("Type")
                                .HasColumnType("int");

                            b1.Property<Guid>("VehicleId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<Guid?>("VehicleId1")
                                .HasColumnType("uniqueidentifier");

                            b1.HasKey("Id");

                            b1.HasIndex("VehicleId");

                            b1.HasIndex("VehicleId1");

                            b1.ToTable("MaintenanceRecord");

                            b1.WithOwner()
                                .HasForeignKey("VehicleId");

                            b1.HasOne("FleetTracker.Services.Core.Models.Vehicle", "Vehicle")
                                .WithMany()
                                .HasForeignKey("VehicleId1");

                            b1.Navigation("Vehicle");
                        });

                    b.Navigation("MaintenanceHistory");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Customer", b =>
                {
                    b.Navigation("RentalHistory");
                });

            modelBuilder.Entity("FleetTracker.Services.Core.Models.Vehicle", b =>
                {
                    b.Navigation("RentalHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
