<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\FleetTracker.Services.Application\FleetTracker.Services.Application.csproj" />
    <ProjectReference Include="..\FleetTracker.Services.Core\FleetTracker.Services.Core.csproj" />
    <ProjectReference Include="..\..\FleetTracker.ServiceDefaults\FleetTracker.ServiceDefaults.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="10.0.8" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.8" />
    <PackageReference Include="Newtonsoft.Json" Version="13.0.4" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <UserSecretsId>f4f2adaf-bef6-4f3f-a5f8-9462b1d08b22</UserSecretsId>
  </PropertyGroup>

</Project>
